New-Item -Path C:\INFORMESPROCESOS, C:\INFORMESSERVICIOS, C:\BACKUP -ItemType Directory
New-Item -Path C:\INFORMESPROCESOS\INFORMESPROCESOS.TXT -ItemType File
New-Item -Path C:\INFORMESSERVICIOS\INFORMESSERVICIOS.TXT -ItemType File
New-Item -Path C:\INFORMESSERVICIOS\BACKUP.TXT -ItemType File